// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAttendanceSystem.Infrastructure.Persistence;

#nullable disable

namespace SmartAttendanceSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250716085013_AddGraduteRole")]
    partial class AddGraduteRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permissions",
                            ClaimValue = "courses:read",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permissions",
                            ClaimValue = "courses:modify",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permissions",
                            ClaimValue = "departments:read",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permissions",
                            ClaimValue = "departments:modify",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permissions",
                            ClaimValue = "students:read",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permissions",
                            ClaimValue = "students:create",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permissions",
                            ClaimValue = "students:courses",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permissions",
                            ClaimValue = "attendance:read",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "permissions",
                            ClaimValue = "attendance:remove",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:admin",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:match",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:add",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:action",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:register",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "permissions",
                            ClaimValue = "Role:read",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "permissions",
                            ClaimValue = "Role:add",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "permissions",
                            ClaimValue = "Role:update",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "permissions",
                            ClaimValue = "user:read",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "permissions",
                            ClaimValue = "user:add",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "permissions",
                            ClaimValue = "user:update",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "permissions",
                            ClaimValue = "user:toggle-status",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "permissions",
                            ClaimValue = "user:unlock",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "permissions",
                            ClaimValue = "courses:read",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "permissions",
                            ClaimValue = "departments:read",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "permissions",
                            ClaimValue = "students:read",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "permissions",
                            ClaimValue = "students:create",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "permissions",
                            ClaimValue = "attendance:read",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "permissions",
                            ClaimValue = "attendance:remove",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:match",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:add",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "permissions",
                            ClaimValue = "fingerprint:action",
                            RoleId = "0194bd46-ceca-7ea4-9d02-9e268a031756"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "E589330B-4F0E-451F-BE37-86519AAFC11A",
                            RoleId = "0194ba0b-a50d-7568-b187-227d0faed2e9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0194ba0b-a50d-7568-b187-227d0faed2e9",
                            ConcurrencyStamp = "0194ba0b-a50d-7568-b187-227ea7268643",
                            IsDefault = false,
                            IsDisabled = false,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "0194ba0b-a50d-7568-b187-2279f6b03b05",
                            ConcurrencyStamp = "0194ba0b-a50d-7568-b187-227aba8bc12f",
                            IsDefault = false,
                            IsDisabled = false,
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "0194bd46-ceca-7ea4-9d02-9e268a031756",
                            ConcurrencyStamp = "0194bd47-1793-75b0-a10b-9de81d580d84",
                            IsDefault = true,
                            IsDisabled = false,
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "01981255-1cb9-7997-ac73-b1213daf4a8a",
                            ConcurrencyStamp = "01981255-526f-71af-b4cb-492dc3aef871",
                            IsDefault = false,
                            IsDisabled = false,
                            Name = "Graduate",
                            NormalizedName = "GRADUATE"
                        });
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationCodeExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "E589330B-4F0E-451F-BE37-86519AAFC11A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0194b8e5-7a29-7829-925e-f718a0ca8ba2",
                            Email = "Admin@SAS.com",
                            EmailConfirmed = true,
                            IsDisabled = false,
                            LockoutEnabled = false,
                            Name = "SAS Admin",
                            NormalizedEmail = "ADMIN@SAS.COM",
                            NormalizedUserName = "ADMIN@SAS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFaOdqUF6MPmAVtOw2LQ65EhwUw6gjsiHamXzDnwfLMBf+cg5DgcLGQm7aaFmjkgQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "F15E8DE749FC4ABB817E6F6B54EA4ADB",
                            TwoFactorEnabled = false,
                            UserName = "Admin@SAS.com"
                        });
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "r212",
                            Level = 2,
                            Name = "Linear Algebra 1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "r216",
                            Level = 2,
                            Name = "Numerical Analysis 1"
                        },
                        new
                        {
                            Id = 3,
                            Code = "r266",
                            Level = 2,
                            Name = "Introduction To Information Systems"
                        },
                        new
                        {
                            Id = 4,
                            Code = "r262",
                            Level = 2,
                            Name = "Object-Oriented Programming"
                        },
                        new
                        {
                            Id = 5,
                            Code = "r264",
                            Level = 2,
                            Name = "Computer Networks 1"
                        },
                        new
                        {
                            Id = 6,
                            Code = "r242",
                            Level = 2,
                            Name = "Probability Theory 1"
                        },
                        new
                        {
                            Id = 7,
                            Code = "r362",
                            Level = 4,
                            Name = "Advanced Operating Systems"
                        },
                        new
                        {
                            Id = 8,
                            Code = "r366",
                            Level = 4,
                            Name = "Web Programming Project"
                        },
                        new
                        {
                            Id = 9,
                            Code = "r318",
                            Level = 3,
                            Name = "Operations Research"
                        },
                        new
                        {
                            Id = 10,
                            Code = "r364",
                            Level = 4,
                            Name = "Computer Graphics"
                        },
                        new
                        {
                            Id = 11,
                            Code = "r372",
                            Level = 4,
                            Name = "Logic Programming"
                        },
                        new
                        {
                            Id = 12,
                            Code = "r368",
                            Level = 4,
                            Name = "Graph Theory"
                        },
                        new
                        {
                            Id = 13,
                            Code = "r211",
                            Level = 2,
                            Name = "Calculus 2"
                        },
                        new
                        {
                            Id = 14,
                            Code = "r213",
                            Level = 2,
                            Name = "Ordinary Differential Equations"
                        },
                        new
                        {
                            Id = 15,
                            Code = "r263",
                            Level = 2,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 16,
                            Code = "r265",
                            Level = 2,
                            Name = "Computer Architecture"
                        },
                        new
                        {
                            Id = 17,
                            Code = "r261",
                            Level = 2,
                            Name = "Structured Programming Basics"
                        },
                        new
                        {
                            Id = 18,
                            Code = "r243",
                            Level = 2,
                            Name = "Statistical Theory"
                        },
                        new
                        {
                            Id = 19,
                            Code = "r311",
                            Level = 3,
                            Name = "Abstract Algebra 1"
                        },
                        new
                        {
                            Id = 20,
                            Code = "r315",
                            Level = 3,
                            Name = "Ordinary Differential Equation Theory"
                        },
                        new
                        {
                            Id = 21,
                            Code = "r365",
                            Level = 4,
                            Name = "Operating Systems"
                        },
                        new
                        {
                            Id = 22,
                            Code = "r367",
                            Level = 3,
                            Name = "Computer Networks 2"
                        },
                        new
                        {
                            Id = 23,
                            Code = "r361",
                            Level = 3,
                            Name = "Algorithm Design And Analysis"
                        },
                        new
                        {
                            Id = 24,
                            Code = "r363",
                            Level = 4,
                            Name = "Web Programming"
                        },
                        new
                        {
                            Id = 25,
                            Code = "r463",
                            Level = 2,
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 26,
                            Code = "r471",
                            Level = 4,
                            Name = "Advanced Computer Graphics"
                        },
                        new
                        {
                            Id = 27,
                            Code = "r461",
                            Level = 2,
                            Name = "Formal Languages"
                        },
                        new
                        {
                            Id = 28,
                            Code = "r465",
                            Level = 3,
                            Name = "Image Processing"
                        },
                        new
                        {
                            Id = 29,
                            Code = "r469",
                            Level = 3,
                            Name = "Signal Processing"
                        },
                        new
                        {
                            Id = 30,
                            Code = "r467",
                            Level = 4,
                            Name = "Parallel Processing"
                        },
                        new
                        {
                            Id = 31,
                            Code = "r233",
                            Level = 2,
                            Name = "Dynamics 2"
                        },
                        new
                        {
                            Id = 32,
                            Code = "r215",
                            Level = 2,
                            Name = "Solid Geometry"
                        },
                        new
                        {
                            Id = 33,
                            Code = "r231",
                            Level = 2,
                            Name = "Statics 2"
                        },
                        new
                        {
                            Id = 34,
                            Code = "r335",
                            Level = 3,
                            Name = "Extended Analysis And General Relativity"
                        },
                        new
                        {
                            Id = 35,
                            Code = "r313",
                            Level = 3,
                            Name = "Real Analysis"
                        },
                        new
                        {
                            Id = 36,
                            Code = "r331",
                            Level = 3,
                            Name = "Electrostatics"
                        },
                        new
                        {
                            Id = 37,
                            Code = "r333",
                            Level = 3,
                            Name = "Analytical Mechanics"
                        },
                        new
                        {
                            Id = 38,
                            Code = "r431",
                            Level = 4,
                            Name = "Statistical Mechanics"
                        },
                        new
                        {
                            Id = 39,
                            Code = "r433",
                            Level = 4,
                            Name = "Fluid Theory 1"
                        },
                        new
                        {
                            Id = 40,
                            Code = "413",
                            Level = 4,
                            Name = "Functional Analysis"
                        },
                        new
                        {
                            Id = 41,
                            Code = "r415",
                            Level = 4,
                            Name = "Complex Analysis"
                        },
                        new
                        {
                            Id = 42,
                            Code = "r414",
                            Level = 4,
                            Name = "Partial Differential Equations 1"
                        },
                        new
                        {
                            Id = 43,
                            Code = "r214",
                            Level = 2,
                            Name = "Mathematical Analysis"
                        },
                        new
                        {
                            Id = 44,
                            Code = "r234",
                            Level = 2,
                            Name = "Vector Analysis"
                        },
                        new
                        {
                            Id = 45,
                            Code = "r232",
                            Level = 2,
                            Name = "Rigid Body Mechanics"
                        },
                        new
                        {
                            Id = 46,
                            Code = "r218",
                            Level = 2,
                            Name = "Special Functions"
                        },
                        new
                        {
                            Id = 47,
                            Code = "r314",
                            Level = 3,
                            Name = "Topology 1"
                        },
                        new
                        {
                            Id = 48,
                            Code = "r316",
                            Level = 3,
                            Name = "Differential Geometry"
                        },
                        new
                        {
                            Id = 49,
                            Code = "r312",
                            Level = 3,
                            Name = "Abstract Algebra 2"
                        },
                        new
                        {
                            Id = 50,
                            Code = "r332",
                            Level = 3,
                            Name = "Quantum Mechanics 1"
                        },
                        new
                        {
                            Id = 51,
                            Code = "r334",
                            Level = 3,
                            Name = "Elasticity Theory 1"
                        },
                        new
                        {
                            Id = 52,
                            Code = "f215",
                            Level = 2,
                            Name = "Oscillating Current And Waves"
                        },
                        new
                        {
                            Id = 53,
                            Code = "f213",
                            Level = 2,
                            Name = "Modern Physics"
                        },
                        new
                        {
                            Id = 54,
                            Code = "f211",
                            Level = 2,
                            Name = "Electromagnetism"
                        },
                        new
                        {
                            Id = 55,
                            Code = "f327",
                            Level = 3,
                            Name = "Crystal Physics"
                        },
                        new
                        {
                            Id = 56,
                            Code = "f343",
                            Level = 3,
                            Name = "Statistical Physics"
                        },
                        new
                        {
                            Id = 57,
                            Code = "f365",
                            Level = 3,
                            Name = "Biophysics"
                        },
                        new
                        {
                            Id = 58,
                            Code = "f325",
                            Level = 2,
                            Name = "Solid State Physics 1"
                        },
                        new
                        {
                            Id = 59,
                            Code = "f333",
                            Level = 4,
                            Name = "Nuclear Physics 1"
                        },
                        new
                        {
                            Id = 60,
                            Code = "f371",
                            Level = 3,
                            Name = "Atomic Physics 2"
                        },
                        new
                        {
                            Id = 61,
                            Code = "f423",
                            Level = 4,
                            Name = "Solid State Physics 2"
                        },
                        new
                        {
                            Id = 62,
                            Code = "f431",
                            Level = 4,
                            Name = "Nuclear Physics 2"
                        },
                        new
                        {
                            Id = 63,
                            Code = "f441",
                            Level = 4,
                            Name = "Electrodynamics"
                        },
                        new
                        {
                            Id = 64,
                            Code = "f477",
                            Level = 3,
                            Name = "Spectral Analysis"
                        },
                        new
                        {
                            Id = 65,
                            Code = "f445",
                            Level = 3,
                            Name = "Quantum Mechanics 2"
                        },
                        new
                        {
                            Id = 66,
                            Code = "f479",
                            Level = 4,
                            Name = "Molecular Physics"
                        },
                        new
                        {
                            Id = 67,
                            Code = "f212",
                            Level = 4,
                            Name = "Physical Optics"
                        },
                        new
                        {
                            Id = 68,
                            Code = "f214",
                            Level = 4,
                            Name = "Thermodynamics"
                        },
                        new
                        {
                            Id = 69,
                            Code = "f272",
                            Level = 4,
                            Name = "Atomic Physics 1"
                        },
                        new
                        {
                            Id = 70,
                            Code = "f342",
                            Level = 3,
                            Name = "Quantum Physics 1"
                        },
                        new
                        {
                            Id = 71,
                            Code = "f384",
                            Level = 3,
                            Name = "Plasma Physics"
                        },
                        new
                        {
                            Id = 72,
                            Code = "f324",
                            Level = 3,
                            Name = "Electronics 1"
                        },
                        new
                        {
                            Id = 73,
                            Code = "f392",
                            Level = 3,
                            Name = "Environmental Physics"
                        },
                        new
                        {
                            Id = 74,
                            Code = "k213",
                            Level = 4,
                            Name = "Organic Chemistry 3"
                        },
                        new
                        {
                            Id = 75,
                            Code = "k211",
                            Level = 4,
                            Name = "Organic Chemistry 2"
                        },
                        new
                        {
                            Id = 76,
                            Code = "k241",
                            Level = 4,
                            Name = "Volumetric And Gravimetric Analysis"
                        },
                        new
                        {
                            Id = 77,
                            Code = "k231",
                            Level = 4,
                            Name = "Kinetics And Acid Base"
                        },
                        new
                        {
                            Id = 78,
                            Code = "241",
                            Level = 4,
                            Name = "Mathematical Statistics"
                        },
                        new
                        {
                            Id = 79,
                            Code = "k221",
                            Level = 4,
                            Name = "Representative Elements Chemistry"
                        },
                        new
                        {
                            Id = 80,
                            Code = "k311",
                            Level = 3,
                            Name = "Physical Organic Chemistry"
                        },
                        new
                        {
                            Id = 81,
                            Code = "k341",
                            Level = 3,
                            Name = "Electrochemical And Chromatographic Methods"
                        },
                        new
                        {
                            Id = 82,
                            Code = "k313",
                            Level = 3,
                            Name = "Heterocyclic Rings And Dyes Chemistry"
                        },
                        new
                        {
                            Id = 83,
                            Code = "k331",
                            Level = 3,
                            Name = "Solid And Colloidal Chemistry"
                        },
                        new
                        {
                            Id = 84,
                            Code = "k315",
                            Level = 3,
                            Name = "Natural Products And Polymers Chemistry"
                        },
                        new
                        {
                            Id = 85,
                            Code = "k321",
                            Level = 3,
                            Name = "Coordination Chemistry And Electrochemistry"
                        },
                        new
                        {
                            Id = 86,
                            Code = "k441",
                            Level = 4,
                            Name = "Instrumental Analysis 1"
                        },
                        new
                        {
                            Id = 87,
                            Code = "k411",
                            Level = 3,
                            Name = "Environmental Organic Chemistry"
                        },
                        new
                        {
                            Id = 88,
                            Code = "k413",
                            Level = 4,
                            Name = "Petroleum And Petrochemicals Chemistry"
                        },
                        new
                        {
                            Id = 89,
                            Code = "k431",
                            Level = 4,
                            Name = "Electrochemistry And Corrosion"
                        },
                        new
                        {
                            Id = 90,
                            Code = "k433",
                            Level = 3,
                            Name = "Thermal Analysis"
                        },
                        new
                        {
                            Id = 91,
                            Code = "k214",
                            Level = 2,
                            Name = "Organic Chemistry 6"
                        },
                        new
                        {
                            Id = 92,
                            Code = "k234",
                            Level = 2,
                            Name = "Nuclear And Laser Chemistry"
                        },
                        new
                        {
                            Id = 93,
                            Code = "k216",
                            Level = 2,
                            Name = "Organic Chemistry 7"
                        },
                        new
                        {
                            Id = 94,
                            Code = "k212",
                            Level = 2,
                            Name = "Organic Chemistry 5"
                        },
                        new
                        {
                            Id = 95,
                            Code = "k222",
                            Level = 2,
                            Name = "Transition Elements Chemistry 1"
                        },
                        new
                        {
                            Id = 96,
                            Code = "k232",
                            Level = 2,
                            Name = "Thermodynamics 1"
                        },
                        new
                        {
                            Id = 97,
                            Code = "k324",
                            Level = 3,
                            Name = "Transition Elements Chemistry 2 And Cement"
                        },
                        new
                        {
                            Id = 98,
                            Code = "k334",
                            Level = 3,
                            Name = "Thermodynamics 2 And Spectrum"
                        },
                        new
                        {
                            Id = 99,
                            Code = "k316",
                            Level = 3,
                            Name = "Photochemistry And Cyclo Reactions"
                        });
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chemistry"
                        });
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.DepartmentCourses", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("DepartmentCourses");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 3
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 4
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 5
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 6
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 7
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 8
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 9
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 10
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 11
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 12
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 13
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 14
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 15
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 16
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 17
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 18
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 19
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 20
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 21
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 22
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 23
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 24
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 25
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 26
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 27
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 28
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 29
                        },
                        new
                        {
                            DepartmentId = 1,
                            CourseId = 30
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 13
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 14
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 19
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 20
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 31
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 32
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 33
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 34
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 35
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 36
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 37
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 38
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 39
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 40
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 41
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 42
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 43
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 44
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 45
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 46
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 47
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 48
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 49
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 50
                        },
                        new
                        {
                            DepartmentId = 2,
                            CourseId = 51
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 1
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 2
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 13
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 14
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 33
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 44
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 52
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 53
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 54
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 55
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 56
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 57
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 58
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 59
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 60
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 61
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 62
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 63
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 64
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 65
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 66
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 67
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 68
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 69
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 70
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 71
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 72
                        },
                        new
                        {
                            DepartmentId = 3,
                            CourseId = 73
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 74
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 75
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 76
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 77
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 78
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 79
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 80
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 81
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 82
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 83
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 84
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 85
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 86
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 87
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 88
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 89
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 90
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 91
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 92
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 93
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 94
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 95
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 96
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 97
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 98
                        },
                        new
                        {
                            DepartmentId = 4,
                            CourseId = 99
                        });
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("FingerId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FingerId")
                        .IsUnique()
                        .HasFilter("[FingerId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAttendanceSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.ApplicationUser", b =>
                {
                    b.OwnsMany("SmartAttendanceSystem.Core.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.Attendance", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAttendanceSystem.Core.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartAttendanceSystem.Core.Entities.Weeks", "Weeks", b1 =>
                        {
                            b1.Property<int>("AttendanceId")
                                .HasColumnType("int");

                            b1.Property<bool?>("Week1")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week10")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week11")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week12")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week2")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week3")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week4")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week5")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week6")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week7")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week8")
                                .HasColumnType("bit");

                            b1.Property<bool?>("Week9")
                                .HasColumnType("bit");

                            b1.HasKey("AttendanceId");

                            b1.ToTable("Weeks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AttendanceId");
                        });

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.DepartmentCourses", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAttendanceSystem.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.Student", b =>
                {
                    b.HasOne("SmartAttendanceSystem.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartAttendanceSystem.Core.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("SmartAttendanceSystem.Core.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartAttendanceSystem.Core.Entities.Student", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
